-- Produtos de teste com sistema de recomendação inteligente

-- Fibra Óptica PF
INSERT INTO ecommerce_products (
  nome, descricao, categoria, operadora, velocidade, franquia,
  preco, preco_instalacao, fidelidade, tipo_pessoa, beneficios,
  ativo, destaque, ordem,
  modalidade, uso_recomendado, limite_dispositivos_min, limite_dispositivos_max,
  badge_texto, texto_decisao, score_base
) VALUES 
(
  'Fibra 300 Mega',
  'Internet ultrarrápida para toda família',
  'fibra',
  'V',
  '300 Mbps',
  'Ilimitado',
  9900,
  0,
  12,
  'PF',
  ARRAY['Wi-Fi grátis', 'Instalação grátis', 'App de controle'],
  true,
  true,
  1,
  'ambos',
  ARRAY['streaming', 'basico'],
  1,
  5,
  'Mais Vendido',
  'Velocidade ideal para assistir Netflix, YouTube e navegar nas redes sociais com até 5 dispositivos conectados simultaneamente.',
  75
),
(
  'Fibra 500 Mega',
  'Alta velocidade para trabalho e entretenimento',
  'fibra',
  'C',
  '500 Mbps',
  'Ilimitado',
  12900,
  0,
  12,
  'PF',
  ARRAY['Wi-Fi 6 grátis', 'Instalação grátis', 'Suporte prioritário', 'Cloud backup 50GB'],
  true,
  true,
  2,
  'ambos',
  ARRAY['trabalho', 'streaming', 'jogos'],
  3,
  8,
  'Recomendado',
  'Perfeito para home office, videochamadas em HD, streaming 4K e jogos online sem lag. Suporta até 8 dispositivos.',
  85
),
(
  'Fibra 1 Giga',
  'Máxima velocidade para quem não abre mão de performance',
  'fibra',
  'T',
  '1 Gbps',
  'Ilimitado',
  19900,
  0,
  12,
  'PF',
  ARRAY['Wi-Fi 6E grátis', 'Instalação grátis', 'Suporte 24/7', 'Cloud backup 100GB', 'IP fixo'],
  true,
  true,
  3,
  'ambos',
  ARRAY['trabalho', 'streaming', 'jogos'],
  5,
  15,
  'Ultra Velocidade',
  'A escolha dos gamers e profissionais. Download de jogos e arquivos pesados em minutos, streaming 8K e múltiplos dispositivos sem perda de velocidade.',
  95
),

-- Fibra Óptica PJ
(
  'Fibra Empresarial 300 Mega',
  'Internet estável para pequenas empresas',
  'fibra',
  'V',
  '300 Mbps',
  'Ilimitado',
  14900,
  0,
  24,
  'PJ',
  ARRAY['IP fixo', 'SLA 99%', 'Suporte técnico', 'Roteador empresarial'],
  true,
  false,
  10,
  'ambos',
  ARRAY['trabalho', 'equipe'],
  5,
  10,
  'Pequenas Empresas',
  'Conexão confiável com SLA garantido para manter sua operação sempre online. Ideal para escritórios com até 10 colaboradores.',
  70
),
(
  'Fibra Empresarial 1 Giga',
  'Alta performance para médias empresas',
  'fibra',
  'C',
  '1 Gbps',
  'Ilimitado',
  29900,
  0,
  24,
  'PJ',
  ARRAY['IP fixo', 'SLA 99.5%', 'Suporte 24/7', 'Roteador empresarial', 'Cloud backup 500GB'],
  true,
  true,
  11,
  'ambos',
  ARRAY['trabalho', 'equipe'],
  10,
  30,
  'Médias Empresas',
  'Velocidade e estabilidade para operações críticas, videoconferências simultâneas e transferência de grandes arquivos. Comporta até 30 usuários.',
  90
),

-- Móvel PF
(
  'Móvel 20GB',
  'Plano completo com apps ilimitados',
  'movel',
  'V',
  '4G/5G',
  '20GB + Apps',
  4990,
  0,
  0,
  'PF',
  ARRAY['WhatsApp ilimitado', 'Instagram ilimitado', 'Portabilidade grátis', 'Roaming nacional'],
  true,
  true,
  20,
  'portabilidade',
  ARRAY['basico', 'streaming'],
  1,
  1,
  'Apps Ilimitados',
  'Use WhatsApp, Instagram, Facebook e Twitter sem descontar da sua franquia. 20GB para navegar e assistir vídeos.',
  80
),
(
  'Móvel 50GB',
  'Liberdade total para navegar',
  'movel',
  'C',
  '4G/5G',
  '50GB + Apps',
  7990,
  0,
  0,
  'PF',
  ARRAY['Todas as redes sociais ilimitadas', 'Waze ilimitado', 'Portabilidade grátis', 'Roaming internacional'],
  true,
  false,
  21,
  'portabilidade',
  ARRAY['streaming', 'jogos'],
  1,
  1,
  'Franquia Generosa',
  'Navegue, assista e jogue sem preocupação. 50GB é franquia suficiente para um mês inteiro de uso intenso.',
  75
),

-- Móvel PJ
(
  'Móvel Empresarial 100GB',
  'Plano corporativo para equipes',
  'movel',
  'T',
  '4G/5G',
  '100GB por linha',
  12990,
  0,
  12,
  'PJ',
  ARRAY['Gestão centralizada', 'Apps corporativos ilimitados', 'Roaming internacional', 'Suporte dedicado'],
  true,
  true,
  30,
  'novo',
  ARRAY['trabalho', 'equipe'],
  1,
  1,
  'Plano Corporativo',
  'Mantenha sua equipe conectada com franquia generosa e ferramentas de gestão. Preço por linha com desconto progressivo a partir de 5 linhas.',
  85
),

-- Combos
(
  'Combo Fibra 500 + TV',
  'Internet + 100 canais HD',
  'combo',
  'V',
  '500 Mbps',
  'Ilimitado',
  17900,
  0,
  12,
  'PF',
  ARRAY['100 canais HD', 'Decoder 4K', 'Wi-Fi 6', 'Gravação em nuvem', 'Paramount+'],
  true,
  true,
  40,
  'ambos',
  ARRAY['streaming', 'basico'],
  3,
  8,
  'Combo Popular',
  'Economize combinando internet ultra rápida com TV por assinatura. Assista seus canais favoritos em qualidade HD/4K.',
  80
),

-- Office 365
(
  'Microsoft 365 Business Basic',
  'Produtividade na nuvem para pequenas empresas',
  'office365',
  'V',
  NULL,
  NULL,
  2490,
  0,
  12,
  'PJ',
  ARRAY['Word, Excel, PowerPoint online', 'Teams', '1TB OneDrive', 'Exchange 50GB', 'Suporte técnico'],
  true,
  false,
  50,
  'novo',
  ARRAY['trabalho', 'equipe'],
  1,
  10,
  'Essencial',
  'Ferramentas completas do Office na web para sua equipe trabalhar de qualquer lugar com total segurança.',
  75
),
(
  'Microsoft 365 Business Standard',
  'Office completo + aplicativos desktop',
  'office365',
  'V',
  NULL,
  NULL,
  4990,
  0,
  12,
  'PJ',
  ARRAY['Office desktop completo', 'Teams Premium', '1TB OneDrive', 'Exchange 50GB', 'Suporte prioritário', 'SharePoint'],
  true,
  true,
  51,
  'novo',
  ARRAY['trabalho', 'equipe'],
  1,
  50,
  'Mais Completo',
  'Todas as ferramentas do Office para instalar no computador + recursos premium de colaboração e videoconferência.',
  90
);

SELECT 'Produtos de teste inseridos com sucesso!' as resultado;
